[build-system]
requires = ["setuptools", "pybind11", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3{9,10,11,12,13}-*"
archs = ["auto64"]
test-sources = ["tests"]
test-command = "python -m unittest -v tests.basic"

[tool.cibuildwheel.macos]
environment = { MACOSX_DEPLOYMENT_TARGET = "10.14" }
